import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Breadcrumb } from './Breadcrumb';

const meta: Meta<typeof Breadcrumb> = {
    title: 'Example/Breadcrumb',
    tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof Breadcrumb>;

export const AutogeneratedBreadcrumb: Story = {
    render: args => {
        return <Breadcrumb {...args} />;
    },
    args: {
        separator: '/',
        maxItems: 4,
    },
    parameters: {
        docs: {
            description: {
                story: 'If no children are provided, the breadcrumb is autogenerated based on React-admin routing and resources.',
            },
        },
    },
};
